/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardNotificacoesRouteImport } from './routes/dashboard.notificacoes'
import { Route as DashboardGamesRouteImport } from './routes/dashboard.games'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardCatalogoRouteImport } from './routes/dashboard.catalogo'
import { Route as DashboardApresentacaoRouteImport } from './routes/dashboard.apresentacao'
import { Route as DashboardAppsRouteImport } from './routes/dashboard.apps'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificacoesRoute = DashboardNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGamesRoute = DashboardGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCatalogoRoute = DashboardCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApresentacaoRoute = DashboardApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/catalogo': typeof CatalogoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/dashboard/apps': typeof DashboardAppsRoute
  '/dashboard/apresentacao': typeof DashboardApresentacaoRoute
  '/dashboard/catalogo': typeof DashboardCatalogoRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/games': typeof DashboardGamesRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/catalogo': typeof CatalogoRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/dashboard/apps': typeof DashboardAppsRoute
  '/dashboard/apresentacao': typeof DashboardApresentacaoRoute
  '/dashboard/catalogo': typeof DashboardCatalogoRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/games': typeof DashboardGamesRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/catalogo': typeof CatalogoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/dashboard/apps': typeof DashboardAppsRoute
  '/dashboard/apresentacao': typeof DashboardApresentacaoRoute
  '/dashboard/catalogo': typeof DashboardCatalogoRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/games': typeof DashboardGamesRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/apresentacao'
    | '/catalogo'
    | '/dashboard'
    | '/games'
    | '/login'
    | '/dashboard/apps'
    | '/dashboard/apresentacao'
    | '/dashboard/catalogo'
    | '/dashboard/configuracoes'
    | '/dashboard/games'
    | '/dashboard/notificacoes'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/apresentacao'
    | '/catalogo'
    | '/games'
    | '/login'
    | '/dashboard/apps'
    | '/dashboard/apresentacao'
    | '/dashboard/catalogo'
    | '/dashboard/configuracoes'
    | '/dashboard/games'
    | '/dashboard/notificacoes'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/apresentacao'
    | '/catalogo'
    | '/dashboard'
    | '/games'
    | '/login'
    | '/dashboard/apps'
    | '/dashboard/apresentacao'
    | '/dashboard/catalogo'
    | '/dashboard/configuracoes'
    | '/dashboard/games'
    | '/dashboard/notificacoes'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  CatalogoRoute: typeof CatalogoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notificacoes': {
      id: '/dashboard/notificacoes'
      path: '/notificacoes'
      fullPath: '/dashboard/notificacoes'
      preLoaderRoute: typeof DashboardNotificacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/games': {
      id: '/dashboard/games'
      path: '/games'
      fullPath: '/dashboard/games'
      preLoaderRoute: typeof DashboardGamesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/catalogo': {
      id: '/dashboard/catalogo'
      path: '/catalogo'
      fullPath: '/dashboard/catalogo'
      preLoaderRoute: typeof DashboardCatalogoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apresentacao': {
      id: '/dashboard/apresentacao'
      path: '/apresentacao'
      fullPath: '/dashboard/apresentacao'
      preLoaderRoute: typeof DashboardApresentacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apps': {
      id: '/dashboard/apps'
      path: '/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardApresentacaoRoute: typeof DashboardApresentacaoRoute
  DashboardCatalogoRoute: typeof DashboardCatalogoRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardGamesRoute: typeof DashboardGamesRoute
  DashboardNotificacoesRoute: typeof DashboardNotificacoesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardApresentacaoRoute: DashboardApresentacaoRoute,
  DashboardCatalogoRoute: DashboardCatalogoRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardGamesRoute: DashboardGamesRoute,
  DashboardNotificacoesRoute: DashboardNotificacoesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  CatalogoRoute: CatalogoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
